### ISSUE TITLE
connect to server fail

### ISSUE THREAD

**Issue by ozuit** [Vidyo/vidyoplatform-connector-react-native#1]
Hi bro!
I found a configuration code to connect to the server but I don't know exactly what these parameters are and where to find them, I tried it with my trial account but it failed. Please give me a specific example.
Thank you!
![alt text](https://ezcrm.vn/photos/upload/2020/Screen%20Shot%202020-03-05%20at%2011.03.37%20AM.png)
https://github.com/Vidyo/vidyoplatform-connector-react-native/blob/cad636fb525b2ca7475d4b60e2ee07e3b08b5604/Page/Conference.js#L30

**Comment by tmelko-vidyo** [comment]
It's VidyoPlatfrom sample (different connection infrastructure). Have you tried Vidyo.io:
https://github.com/Vidyo/vidyo.io-connector-react-native
token-based sample?
Doc: https://developer.vidyo.io

**Comment by ozuit** [comment]
ok thank you so much!
