### ISSUE TITLE
switch camera (front to back)

### ISSUE THREAD

**Issue by Amin-Shah** [Vidyo/vidyoplatform-connector-react-native#3]
Hello There,
Is there any way to switch camera during video call.

**Comment by tmelko-vidyo** [comment]
Yes, you have to port: cycleCamera() API. You can do this in the same way as a mute mic or camera. Just add one more exported API and place it under corresponding UI.

**Comment by Amin-Shah** [comment]
Can you please give me example code i have check the java and objective c code and didn't find cycleCamera() imlementation there. i use react native and follow (https://github.com/Vidyo/vidyoplatform-connector-react-native) this repo.

**Comment by Amin-Shah** [comment]
@tmelko-vidyo Can you please give me example code i have check the java and objective c code and didn't find cycleCamera() imlementation there. i use react native and follow (https://github.com/Vidyo/vidyoplatform-connector-react-native) this repo.

**Comment by tmelko-vidyo** [comment]
Sure:
Android connector.cycleCamera(); (implemented in VidyoConnectorView.java)
iOS: [_connector cycleCamera]; (VidyoConnectorView.m)

**Comment by Amin-Shah** [comment]
Hi there,
i have created a function in VidyoConnectorView.java
    public void cycleCamera() {
        connector.cycleCamera();
    }
also i have passed a prop in VideoConnectorView.js and in VideoCall.js

VideoConnectorView.js
cycleCamera: PropTypes.bool,

VideoCall.js
cycleCamera={this.state.cycleCameraButtonState}

**Comment by tmelko-vidyo** [comment]
Updated the sample to have a camera switch option.
Commit: 
https://github.com/Vidyo/vidyoplatform-connector-react-native/commit/416dc391eb6b5c59df42ce99e604d6057c99f381

**Comment by Amin-Shah** [comment]
Thankyou so much for such an amazing service, it works!
